//! The BAS accounts every company starts with: the ones a small Swedish
//! company commonly uses. More can be added per company.

pub(crate) const ACCOUNTS: &[(u16, &str)] = &[
    (1010, "Utvecklingsutgifter"),
    (1030, "Patent"),
    (1050, "Goodwill"),
    (1110, "Byggnader"),
    (1119, "Ackumulerade avskrivningar på byggnader"),
    (1130, "Mark"),
    (1150, "Markanläggningar"),
    (1210, "Maskiner och andra tekniska anläggningar"),
    (
        1219,
        "Ackumulerade avskrivningar på maskiner och andra tekniska anläggningar",
    ),
    (1220, "Inventarier och verktyg"),
    (
        1229,
        "Ackumulerade avskrivningar på inventarier och verktyg",
    ),
    (1240, "Bilar och andra transportmedel"),
    (
        1249,
        "Ackumulerade avskrivningar på bilar och andra transportmedel",
    ),
    (1250, "Datorer"),
    (1259, "Ackumulerade avskrivningar på datorer"),
    (1310, "Andelar i koncernföretag"),
    (1350, "Andelar och värdepapper i andra företag"),
    (1380, "Andra långfristiga fordringar"),
    (1385, "Värde av kapitalförsäkring"),
    (1410, "Lager av råvaror"),
    (1460, "Lager av handelsvaror"),
    (1470, "Pågående arbeten"),
    (1480, "Förskott för varor och tjänster"),
    (1510, "Kundfordringar"),
    (1515, "Osäkra kundfordringar"),
    (1610, "Kortfristiga fordringar hos anställda"),
    (1630, "Avräkning för skatter och avgifter (skattekonto)"),
    (1640, "Skattefordringar"),
    (1650, "Momsfordran"),
    (1680, "Andra kortfristiga fordringar"),
    (1710, "Förutbetalda hyreskostnader"),
    (1720, "Förutbetalda leasingavgifter"),
    (1730, "Förutbetalda försäkringspremier"),
    (1790, "Övriga förutbetalda kostnader och upplupna intäkter"),
    (1910, "Kassa"),
    (1920, "PlusGiro"),
    (1930, "Företagskonto/checkkonto/affärskonto"),
    (1940, "Övriga bankkonton"),
    (2010, "Eget kapital"),
    (2013, "Övriga egna uttag"),
    (2017, "Årets kapitaltillskott"),
    (2018, "Övriga egna insättningar"),
    (2019, "Årets resultat"),
    (2081, "Aktiekapital"),
    (2085, "Uppskrivningsfond"),
    (2086, "Reservfond"),
    (2091, "Balanserad vinst eller förlust"),
    (2093, "Erhållna aktieägartillskott"),
    (2098, "Vinst eller förlust från föregående år"),
    (2099, "Årets resultat"),
    (2123, "Periodiseringsfond 2023"),
    (2124, "Periodiseringsfond 2024"),
    (2125, "Periodiseringsfond 2025"),
    (2126, "Periodiseringsfond 2026"),
    (2150, "Ackumulerade överavskrivningar"),
    (2220, "Avsättningar för garantier"),
    (2350, "Andra långfristiga skulder till kreditinstitut"),
    (2390, "Övriga långfristiga skulder"),
    (2393, "Lån från närstående personer, långfristig del"),
    (2410, "Andra kortfristiga låneskulder till kreditinstitut"),
    (2420, "Förskott från kunder"),
    (2440, "Leverantörsskulder"),
    (2510, "Skatteskulder"),
    (2512, "Beräknad inkomstskatt"),
    (2514, "Beräknad särskild löneskatt på pensionskostnader"),
    (2518, "Betald F-skatt"),
    (2610, "Utgående moms, 25 %"),
    (2611, "Utgående moms på försäljning inom Sverige, 25 %"),
    (2614, "Utgående moms omvänd skattskyldighet, 25 %"),
    (2615, "Utgående moms import av varor, 25 %"),
    (2620, "Utgående moms, 12 %"),
    (2621, "Utgående moms på försäljning inom Sverige, 12 %"),
    (2630, "Utgående moms, 6 %"),
    (2631, "Utgående moms på försäljning inom Sverige, 6 %"),
    (2640, "Ingående moms"),
    (2641, "Debiterad ingående moms"),
    (2645, "Beräknad ingående moms på förvärv från utlandet"),
    (2650, "Redovisningskonto för moms"),
    (2710, "Personalskatt"),
    (2730, "Lagstadgade sociala avgifter och särskild löneskatt"),
    (2731, "Avräkning lagstadgade sociala avgifter"),
    (2732, "Avräkning särskild löneskatt"),
    (2790, "Övriga löneavdrag"),
    (2820, "Kortfristiga skulder till anställda"),
    (2890, "Övriga kortfristiga skulder"),
    (2893, "Skulder till närstående personer, kortfristig del"),
    (2898, "Outtagen vinstutdelning"),
    (2910, "Upplupna löner"),
    (2920, "Upplupna semesterlöner"),
    (2940, "Upplupna lagstadgade sociala och andra avgifter"),
    (2990, "Övriga upplupna kostnader och förutbetalda intäkter"),
    (3001, "Försäljning inom Sverige, 25 % moms"),
    (3002, "Försäljning inom Sverige, 12 % moms"),
    (3003, "Försäljning inom Sverige, 6 % moms"),
    (3004, "Försäljning inom Sverige, momsfri"),
    (3105, "Försäljning varor till land utanför EU"),
    (3106, "Försäljning varor till annat EU-land, momspliktig"),
    (3108, "Försäljning varor till annat EU-land, momsfri"),
    (3305, "Försäljning tjänster till land utanför EU"),
    (3308, "Försäljning tjänster till annat EU-land"),
    (3540, "Faktureringsavgifter"),
    (3730, "Lämnade rabatter"),
    (3740, "Öres- och kronutjämning"),
    (3911, "Hyresintäkter"),
    (
        3960,
        "Valutakursvinster på fordringar och skulder av rörelsekaraktär",
    ),
    (
        3970,
        "Vinst vid avyttring av immateriella och materiella anläggningstillgångar",
    ),
    (3990, "Övriga ersättningar och intäkter"),
    (4010, "Inköp material och varor"),
    (
        4415,
        "Inköpta varor i Sverige, omvänd skattskyldighet, 25 % moms",
    ),
    (
        4425,
        "Inköpta tjänster i Sverige, omvänd skattskyldighet, 25 %",
    ),
    (4515, "Inköp av varor från annat EU-land, 25 %"),
    (4535, "Inköp av tjänster från annat EU-land, 25 %"),
    (4545, "Import av varor, 25 % moms"),
    (4598, "Justering, omvänd moms"),
    (4600, "Legoarbeten och underentreprenader"),
    (4900, "Förändring av lager"),
    (5010, "Lokalhyra"),
    (5020, "El för belysning"),
    (5060, "Städning och renhållning"),
    (5090, "Övriga lokalkostnader"),
    (5410, "Förbrukningsinventarier"),
    (5420, "Programvaror"),
    (5460, "Förbrukningsmaterial"),
    (5500, "Reparation och underhåll"),
    (5611, "Drivmedel för personbilar"),
    (5612, "Försäkring och skatt för personbilar"),
    (5613, "Reparation och underhåll av personbilar"),
    (5615, "Leasing av personbilar"),
    (5800, "Resekostnader"),
    (5810, "Biljetter"),
    (5831, "Kost och logi i Sverige"),
    (5832, "Kost och logi i utlandet"),
    (5910, "Annonsering"),
    (5930, "Reklamtrycksaker och direktreklam"),
    (6071, "Representation, avdragsgill"),
    (6072, "Representation, ej avdragsgill"),
    (6110, "Kontorsmateriel"),
    (6211, "Fast telefoni"),
    (6212, "Mobiltelefon"),
    (6230, "Datakommunikation"),
    (6250, "Postbefordran"),
    (6310, "Företagsförsäkringar"),
    (6420, "Ersättningar till revisor"),
    (6530, "Redovisningstjänster"),
    (6540, "IT-tjänster"),
    (6550, "Konsultarvoden"),
    (6570, "Bankkostnader"),
    (6590, "Övriga externa tjänster"),
    (6970, "Tidningar, tidskrifter och facklitteratur"),
    (6981, "Föreningsavgifter, avdragsgilla"),
    (6982, "Föreningsavgifter, ej avdragsgilla"),
    (6991, "Övriga externa kostnader, avdragsgilla"),
    (6992, "Övriga externa kostnader, ej avdragsgilla"),
    (7010, "Löner till kollektivanställda"),
    (7210, "Löner till tjänstemän"),
    (7220, "Löner till företagsledare"),
    (7290, "Förändring av semesterlöneskuld"),
    (7331, "Skattefria bilersättningar"),
    (7332, "Skattepliktiga bilersättningar"),
    (7385, "Kostnader för fri bil"),
    (7410, "Pensionsförsäkringspremier"),
    (7510, "Arbetsgivaravgifter 31,42 %"),
    (7519, "Sociala avgifter för semester- och löneskulder"),
    (7530, "Särskild löneskatt"),
    (7533, "Särskild löneskatt för pensionskostnader"),
    (7570, "Premier för arbetsmarknadsförsäkringar"),
    (7610, "Utbildning"),
    (7631, "Personalrepresentation, avdragsgill"),
    (7632, "Personalrepresentation, ej avdragsgill"),
    (7690, "Övriga personalkostnader"),
    (7810, "Avskrivningar på immateriella anläggningstillgångar"),
    (7820, "Avskrivningar på byggnader och markanläggningar"),
    (
        7832,
        "Avskrivningar på maskiner och andra tekniska anläggningar",
    ),
    (7834, "Avskrivningar på bilar och andra transportmedel"),
    (7835, "Avskrivningar på datorer"),
    (
        7960,
        "Valutakursförluster på fordringar och skulder av rörelsekaraktär",
    ),
    (
        7970,
        "Förlust vid avyttring av immateriella och materiella anläggningstillgångar",
    ),
    (8310, "Ränteintäkter från omsättningstillgångar"),
    (8314, "Skattefria ränteintäkter"),
    (8410, "Räntekostnader för långfristiga skulder"),
    (8420, "Räntekostnader för kortfristiga skulder"),
    (8423, "Räntekostnader för skatter och avgifter"),
    (8811, "Avsättning till periodiseringsfond"),
    (8819, "Återföring från periodiseringsfond"),
    (8850, "Förändring av överavskrivningar"),
    (8910, "Skatt som belastar årets resultat"),
    (8999, "Årets resultat"),
];
