[package]
name = "doris-web"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
console_error_panic_hook = "0.1"
doris-proto.workspace = true
js-sys = "0.3"
leptos = { version = "0.8", features = ["csr"] }
leptos_router = "0.8"
prost.workspace = true
serde_json.workspace = true
tonic.workspace = true
tonic-web-wasm-client = "0.9"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
webauthn-rs-proto = { workspace = true, features = ["wasm"] }
web-sys = { version = "0.3", features = ["CredentialsContainer", "CredentialCreationOptions", "CredentialRequestOptions", "PublicKeyCredential", "Storage", "StorageEvent", "Document", "Element", "Location", "Navigator", "Window", "Blob", "BlobPropertyBag", "File", "FileList", "HtmlAnchorElement", "HtmlElement", "HtmlInputElement", "Url"] }
