[package]
name = "doris-identity"
version.workspace = true
edition.workspace = true

[dependencies]
base64.workspace = true
doris-eventstore.workspace = true
getrandom.workspace = true
jiff.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
webauthn-rs.workspace = true
webauthn-rs-proto.workspace = true

[dev-dependencies]
url.workspace = true
webauthn-authenticator-rs.workspace = true
tempfile.workspace = true
tokio.workspace = true
